name: UpdateJson

# masterにpushされたら実行 
#on:
#  push:
#    branches:
#      - master

# 毎日0時0分に実行
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  UpdateJson:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: echo test
