name: Tweet0

# masterにpushされたら実行 
on:
  push:
    branches:
      - master

# 毎日0時0分に実行
#on:
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  Tweet0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: echo test
